apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service-name
  namespace: "{{{M3_NAMESPACE}}}"
  # annotations:
  #   kubernetes.io/ingress.class: nginx
  #   nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  rules:
  - host: "{{{POSTS_SERVICE_DNS}}}.ahmedayoub.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pickify-posts-service-name
            port:
              number: 80
  - host: "{{{VOTES_SERVICE_DNS}}}.ahmedayoub.me"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pickify-votes-service-name
            port:
              number: 80